[package]
name = "lab5"
version = "0.1.0"
authors = ["nazzrrg <nazarov.egor2010@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
