[package]
name = "text_handler"
version = "0.1.0"
authors = ["Egor <nazarov.egor2010@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.8"
Inflector = "0.11.4"